---
- hosts: ubuntu2
  become: yes
  tasks:
    - name: Copy bash_file to the server
      copy:
        src: config.sh
        dest: /tmp/config.sh
    - name: Run the bash script
      command: bash /tmp/config.sh
